const fs = require('node:fs')
const path = require('node:path')
const assert = require('node:assert/strict')
const { createRequire } = require('node:module')
const { chromium } = createRequire(path.resolve('docs/ui-redesign-2026-09-25/design-demos/package.json'))('playwright')
const out = path.resolve('artifacts/iter5-refinement/regression')
;(async () => {
  const browser = await chromium.launch({ executablePath: path.join(process.env.LOCALAPPDATA, 'ms-playwright/chromium_headless_shell-1228/chrome-headless-shell-win64/chrome-headless-shell.exe'), headless: true })
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
  const errors = [], posts = [], checks = []
  const check = (name, value) => { assert(value, name); checks.push(name); console.log('PASS', name) }
  page.on('pageerror', e => errors.push(e.message))
  page.on('request', r => { if (r.method() === 'POST' && r.url().includes('/api/dsh-auto-memory/')) posts.push({ path: new URL(r.url()).pathname, body: r.postDataJSON() }) })
  page.on('dialog', d => d.dismiss())
  try {
    const url = fs.readFileSync(path.join(process.env.TEMP, 'iter5-refine-host.log'), 'utf8').match(/http:\/\/127\.0\.0\.1:19388\/\?token=\S+/)[0]
    await page.goto(url)
    if (await page.getByRole('button', { name: '继续', exact: true }).count()) await page.getByRole('button', { name: '继续', exact: true }).click()
    await page.waitForTimeout(500)
    if (await page.getByRole('button', { name: '稍后配置', exact: true }).count()) await page.getByRole('button', { name: '稍后配置', exact: true }).click()
    const c = await page.evaluate(async () => (await (await fetch('/api/dsh-auto-memory/config')).json()).config)
    const qa = path.join(process.env.TEMP, 'dsh-iter5-qa-20260928').replaceAll('\\','/').toLowerCase()
    check('Real host writes isolated from personal memory', c.memoryRoot.replaceAll('\\','/').toLowerCase().startsWith(qa) && c.userMemoryDir.replaceAll('\\','/').toLowerCase().startsWith(qa))
    await page.evaluate(async () => { const r = await fetch('/api/dsh-auto-memory/config', { method: 'POST', headers: { 'content-type':'application/json' }, body: JSON.stringify({ semanticEngineMode:'auto', jsDecideCooldownRounds:1 }) }); if (!r.ok) throw Error('Isolated test setup failed') })
    if (!await page.getByRole('treeitem', { name: /^UI 集成隔离验收/ }).first().isVisible()) await page.getByText('Iter5 隔离验收', { exact: true }).first().click()
    await page.getByRole('treeitem', { name: /^UI 集成隔离验收/ }).first().click()
    await page.getByRole('tab', { name: '记忆', exact: true }).click()
    await page.getByRole('button', { name: '开发版', exact: true }).click()
    await page.locator('[data-iter5] h1').waitFor()
    await page.waitForTimeout(350)
    check('Skin mounted through actual conversation.view', await page.locator('[data-iter5]').count() === 1)
    check('Inner scroller ends above host composer', await page.locator('[data-iter5]').evaluate(el => el.getBoundingClientRect().bottom <= document.querySelector('[data-composer-card]').getBoundingClientRect().top + 2))
    async function nav(id) {
      const notice=page.locator('[data-shell-overlay]').getByRole('button',{name:'知道了',exact:true}); if(await notice.isVisible().catch(()=>false))await notice.click()
      if (!await page.locator('[data-i5-nav="'+id+'"]').isVisible()) await page.getByRole('button', { name: '打开导航', exact: true }).click()
      await page.locator('[data-i5-nav="'+id+'"]').click()
      await page.waitForTimeout(400)
    }
    const ids = ['home','library','handoff','calendar','skills','recall','mindmap','storage','settings']
    for (const id of ids) {
      await nav(id)
      await page.screenshot({ path: path.join(out, 'live-'+id+'-1440.png') })
      check('Real page '+id+' renders', await page.locator('[data-iter5] h1').count() === 1 && errors.length === 0)
    }
    const setting = page.locator('[data-iter5]')
    await setting.getByRole('radio', { name: '仅词法', exact: true }).click()
    await page.waitForTimeout(350)
    const engineWrite = posts.filter(r => r.path.endsWith('/config')).at(-1)
    check('Engine radio writes immediately, single config key', JSON.stringify(engineWrite?.body) === JSON.stringify({ semanticEngineMode: 'lexical' }))
    check('Engine radio is outside dirty drafts', await page.locator('[data-i5-dirty]').getAttribute('data-i5-dirty') === 'false')
    await setting.getByText('高级：发射模式、判定参数与观测', { exact: true }).click()
    const cooldown = setting.getByRole('spinbutton', { name: '唤起冷却(分钟)', exact: true })
    await cooldown.fill('4')
    await setting.getByRole('button', { name: '保存更改', exact: true }).click()
    await page.waitForTimeout(350)
    check('Actual draft save only writes changed preference', JSON.stringify(posts.filter(r => r.path.endsWith('/config')).at(-1).body) === JSON.stringify({ jsDecideCooldownRounds: 4 }))
    await cooldown.fill('8')
    await page.route('**/api/dsh-auto-memory/config', async route => {
      if (route.request().method() === 'POST') return route.fulfill({ status: 500, contentType: 'application/json', body: JSON.stringify({ error: 'isolated injected failure' }) })
      return route.continue()
    })
    await setting.getByRole('button', { name: '保存更改', exact: true }).click()
    await page.waitForTimeout(250)
    check('Failed write retains browser draft', await cooldown.inputValue() === '8' && await page.locator('[data-i5-dirty]').getAttribute('data-i5-dirty') === 'true')
    await page.unroute('**/api/dsh-auto-memory/config')
    await setting.getByRole('button', { name: '取消修改', exact: true }).click()
    check('Cancel restores saved browser value', await cooldown.inputValue() === '4')
    await setting.getByRole('tab', { name: '引擎', exact: true }).focus()
    await page.keyboard.press('ArrowRight')
    check('WAI-APG settings tab keyboard navigation', await setting.getByRole('tab', { name: '记忆', exact: true }).getAttribute('aria-selected') === 'true')
    await setting.getByRole('tab', { name: '外观与目录', exact: true }).click()
    await page.screenshot({ path: path.join(out, 'live-settings-appearance-1440.png') })
    await setting.getByRole('tab', { name: '行为与维护', exact: true }).click()
    await page.screenshot({ path: path.join(out, 'live-settings-behavior-1440.png') })
    await nav('library')
    await setting.getByRole('button', { name: '追加笔记', exact: true }).click()
    await setting.locator('textarea').fill('Iter5 隔离验收笔记：验证真实追加写入，不含个人数据。记录时刻 '+new Date().toISOString())
    await setting.getByRole('button', { name: '追加', exact: true }).click()
    await page.waitForTimeout(350)
    check('Append note uses real note endpoint', posts.some(r => r.path.endsWith('/note') && r.body.content.includes('Iter5 隔离验收')))
    await setting.getByRole('tab', { name:'检索', exact:true }).click()
    await setting.getByRole('searchbox', { name:'检索记忆', exact:true }).fill('隔离验收')
    await setting.getByRole('button', { name:'检索', exact:true }).click()
    await page.waitForTimeout(500)
    check('Memory search uses real recall with requested limit', posts.some(r=>r.path.endsWith('/recall')&&r.body.query==='隔离验收'&&r.body.limit===8))
    await nav('calendar')
    const eventTitle='日程联调 · '+Date.now()
    await setting.getByRole('button', { name:'+ 添加事项', exact:true }).click()
    const dialog=setting.getByRole('dialog',{name:'添加日程',exact:true})
    await dialog.getByLabel('标题',{exact:true}).fill(eventTitle)
    await dialog.getByLabel('地点',{exact:true}).fill('隔离验收环境')
    await dialog.getByRole('button',{name:'添加日程',exact:true}).click()
    await setting.locator('.i5-event-card').filter({hasText:eventTitle}).waitFor()
    check('Calendar add round-trip renders saved event',await setting.locator('.i5-event-card').filter({hasText:eventTitle}).count()===1)
    await setting.getByRole('button',{name:'标记完成：'+eventTitle,exact:true}).click()
    await page.waitForTimeout(400)
    const finished=await page.evaluate(async title=>(await (await fetch('/api/dsh-auto-memory/calendar')).json()).entries.find(e=>e.title===title),eventTitle)
    check('Calendar completion persisted on host',finished?.done===true)
    page.removeAllListeners('dialog');page.once('dialog',d=>d.accept())
    await setting.getByRole('button',{name:'删除日程：'+eventTitle,exact:true}).click()
    await page.waitForTimeout(400)
    const removed=await page.evaluate(async title=>(await (await fetch('/api/dsh-auto-memory/calendar')).json()).entries.some(e=>e.title===title),eventTitle)
    check('Confirmed calendar deletion persisted',!removed)
    page.on('dialog',d=>d.dismiss())
    await nav('recall')
    if(await setting.locator('.i5-review-row').count()){
      await setting.locator('.i5-feedback button').first().click()
      await page.waitForTimeout(350)
      const feedbackPost=posts.filter(r=>r.path.endsWith('/review-feedback')).at(-1)
      check('A/P/S/H/E feedback accepted by actual host',feedbackPost?.body.choice==='A'&&await setting.getByRole('status').filter({hasText:'已提交反馈'}).count()===1)
      const persisted=await page.evaluate(async id=>(await (await fetch('/api/dsh-auto-memory/review-feedback')).json()).queue.some(r=>r.observationId===id&&r.choice==='A'),feedbackPost.body.observationId)
      check('Feedback is readable from review queue',persisted)
    }
    await nav('home')
    await page.getByRole('button',{name:'专注查看',exact:true}).click()
    check('Focus mode expands inside real host',await page.locator('[data-iter5]').getAttribute('data-focus')==='true')
    await page.evaluate(()=>document.documentElement.setAttribute('data-dsh-theme','dark'))
    await page.waitForTimeout(250)
    check('Skin follows host dark-theme attribute',await page.locator('[data-iter5]').getAttribute('data-deep')==='true')
    await page.screenshot({path:path.join(out,'live-home-dark.png')})
    await page.evaluate(()=>document.documentElement.removeAttribute('data-dsh-theme'))
    await page.getByRole('button',{name:'退出专注查看',exact:true}).click()
    await nav('home')
    for (const width of [768,390]) {
      await page.setViewportSize({ width, height: 900 })
      await page.waitForTimeout(300)
      await page.screenshot({ path: path.join(out, 'live-home-'+width+'.png') })
      check('Home '+width+' no horizontal overflow', await page.locator('.i5-main').evaluate(el => el.scrollWidth <= el.clientWidth + 1))
      await nav('settings')
      await page.screenshot({ path: path.join(out, 'live-settings-'+width+'.png') })
      check('Settings '+width+' no horizontal overflow', await page.locator('.i5-main').evaluate(el => el.scrollWidth <= el.clientWidth + 1))
      await page.getByRole('button', { name: '打开导航', exact: true }).click()
      check('Narrow nav moves focus to close', await page.getByRole('button', { name: '关闭导航', exact: true }).evaluate(el => el === document.activeElement))
      await page.keyboard.press('Escape')
      check('Narrow nav restores focus', await page.getByRole('button', { name: '打开导航', exact: true }).evaluate(el => el === document.activeElement))
      await nav('home')
    }
    await page.setViewportSize({ width: 1440, height: 900 })
    await page.waitForTimeout(300)
    await setting.getByRole('button', { name: '返回经典皮肤', exact: true }).click()
    check('Classic switch removes new skin and injected stylesheet', await page.locator('[data-iter5]').count() === 0 && await page.locator('#dam-skin-v4-style').count() === 0)
    await page.screenshot({ path: path.join(out, 'live-classic-1440.png') })
    check('No uncaught page errors', errors.length === 0)
    fs.writeFileSync(path.join(out, 'live-checks.json'), JSON.stringify({ checks, errors, posts }, null, 2))
  } catch (e) {
    await page.screenshot({ path: path.join(out, 'live-failure.png') }).catch(() => {})
    fs.writeFileSync(path.join(out, 'live-checks.json'), JSON.stringify({ checks, errors, failure: e.message, posts }, null, 2))
    throw e
  } finally { await browser.close() }
})().catch(e => { console.error(e.message.replace(/token=\S+/g, 'token=[redacted]')); process.exitCode = 1 })
