const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict')
const {open,out}=require('./host-session.cjs')
;(async()=>{
 const {browser,page,nav,home,errors}=await open(),checks=[]
 const check=(name,ok)=>{assert(ok,name);checks.push(name);console.log('PASS',name)}
 let restore
 try{
  await page.getByRole('button',{name:'专注查看',exact:true}).click();await nav('home')
  check('Home retains calendar beside recent records',await page.locator('.i5-daily-card').count()===1&&await page.locator('.i5-activity').count()===1)
  await page.screenshot({path:path.join(out,'after-home-1440.png')})
  await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(out,'after-home-390.png')})
  await page.setViewportSize({width:1440,height:900});await nav('library')
  const state=await page.evaluate(async()=>await(await fetch('/api/dsh-auto-memory/state')).json())
  assert(path.resolve(state.userFile).startsWith(home+path.sep))
  const original=fs.readFileSync(state.userFile)
  restore=()=>fs.writeFileSync(state.userFile,original)
  fs.writeFileSync(state.userFile,'# 长正文与英文无空格测试\n\n'+Array.from({length:80},(_,i)=>'第 '+i+' 段：这是隔离验收素材，用于检查长文滚动与来源可发现性。 '+ 'ABCDEFGHIJKLMN'.repeat(6)).join('\n\n'))
  await page.getByRole('button',{name:'刷新当前页',exact:true}).click();await page.waitForTimeout(300)
  const doc=page.locator('.i5-source-card .i5-document')
  check('Long document scrolls internally',await doc.evaluate(e=>e.scrollHeight>e.clientHeight+100))
  check('Long document never hides source below host',await page.locator('.i5-source-origin').evaluate(e=>e.getBoundingClientRect().bottom<=e.closest('.i5-main').getBoundingClientRect().bottom))
  check('Long unbroken English wraps',await page.locator('.i5-main').evaluate(e=>e.scrollWidth<=e.clientWidth+1))
  await page.locator('[data-iter5]').evaluate(e=>e.style.setProperty('--dam-user-scale','1.5'));await page.waitForTimeout(200)
  check('Large type brand is not clipped',await page.locator('.i5-brand strong').evaluate(e=>e.scrollWidth<=e.clientWidth+1))
  check('Large type keeps full source within host',await page.locator('.i5-source-origin').evaluate(e=>e.getBoundingClientRect().bottom<=e.closest('.i5-main').getBoundingClientRect().bottom))
  await page.screenshot({path:path.join(out,'after-library-large-type.png')})
  await page.locator('[data-iter5]').evaluate(e=>e.style.removeProperty('--dam-user-scale'));restore();restore=null
  await nav('settings')
  const root=page.locator('[data-iter5]')
  await root.getByText('高级：发射模式、判定参数与观测',{exact:true}).click()
  const field=root.getByRole('spinbutton',{name:'唤起冷却(分钟)',exact:true})
  const saved=await field.inputValue();await field.fill('9')
  await root.getByRole('tab',{name:'记忆',exact:true}).click();await root.getByRole('tab',{name:/^引擎/}).click()
  check('Settings tabs preserve draft',await field.inputValue()==='9')
  await page.locator('[data-i5-nav=home]').click();check('Rejected leave stays on settings',await root.locator('h1').innerText()==='设置')
  await page.getByRole('button',{name:'刷新当前页',exact:true}).click();check('Rejected refresh preserves draft',await field.inputValue()==='9')
  await root.getByRole('button',{name:'返回经典皮肤',exact:true}).click();check('Rejected classic switch preserves draft',await field.inputValue()==='9')
  await root.getByRole('button',{name:'取消修改',exact:true}).click();check('Cancel restores saved configuration',await field.inputValue()===saved)
  await page.getByRole('button',{name:'刷新当前页',exact:true}).click();await page.waitForTimeout(250)
  check('Clean refresh succeeds',await root.locator('[data-i5-dirty]').getAttribute('data-i5-dirty')==='false')
  check('No page errors',errors.length===0)
 }finally{if(restore)restore();fs.writeFileSync(path.join(out,'edge-results.json'),JSON.stringify({checks,errors},null,2));await browser.close()}
})().catch(e=>{console.error(e);process.exitCode=1})
