const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{createRequire}=require('node:module')
const {chromium}=createRequire('C:/Users/李云龙/dsh-auto-memory/docs/ui-redesign-2026-09-25/design-demos/package.json')('playwright')
;(async()=>{
 const browser=await chromium.launch({executablePath:path.join(process.env.LOCALAPPDATA,'ms-playwright/chromium_headless_shell-1228/chrome-headless-shell-win64/chrome-headless-shell.exe'),headless:true})
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),checks=[],errors=[],evidence=[]
 const check=(name,ok)=>{assert(ok,name);checks.push(name)}
 const capture=async(name,el)=>{await el.scrollIntoViewIfNeeded();await page.waitForTimeout(250);if(process.env.NATIVE_CAPTURE==='1'||(process.env.NATIVE_CAPTURE==='final'&&/^(python|model-picker)/.test(name)))await page.screenshot({path:path.join(__dirname,name+'.png')});const bounds=await el.evaluate(n=>({width:n.clientWidth,scroll:n.scrollWidth,overflow:Array.from(n.querySelectorAll('*')).filter(c=>c.getBoundingClientRect().right>n.getBoundingClientRect().right+1).slice(0,8).map(c=>[c.tagName,c.className,c.clientWidth,c.scrollWidth])}));if(bounds.scroll>bounds.width+1)console.log(name,JSON.stringify(bounds));check(name+' no horizontal overflow',bounds.scroll<=bounds.width+1);evidence.push(name)}
 page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept())
 let imported=0,deleted=0,event=null,config=null,engineChanged=false
 page.on('request',r=>{if(r.url().includes('/migrate-import'))imported++;if(r.url().includes('/storage-manage')&&r.postData()?.includes('"delete"'))deleted++})
 try{
 const url=fs.readFileSync(path.join(process.env.TEMP,'native-ui-host.log'),'utf8').match(/http:\/\/127\.0\.0\.1:19388\/\?token=\S+/)?.[0];assert(url)
 await page.goto(url);await page.waitForTimeout(1800)
 if(await page.getByRole('button',{name:'继续',exact:true}).count())await page.getByRole('button',{name:'继续',exact:true}).click()
 await page.waitForTimeout(500)
 if(await page.getByRole('button',{name:'稍后配置',exact:true}).count())await page.getByRole('button',{name:'稍后配置',exact:true}).click()
 if(await page.locator('[data-dam-tour]').count())await page.keyboard.press('Escape')
 config=await page.evaluate(async()=> (await(await fetch('/api/dsh-auto-memory/config')).json()).config)
 check('isolated fixture roots',config.memoryRoot.includes('dsh-iter5-qa-20260928')&&config.userMemoryDir.includes('dsh-iter5-qa-20260928'))
 if(!await page.getByRole('treeitem',{name:/^UI 集成隔离验收/}).first().isVisible())await page.getByRole('treeitem',{name:'Iter5 隔离验收',exact:true}).click()
 await page.getByRole('treeitem',{name:/^UI 集成隔离验收/}).first().click()
 await page.getByRole('tab',{name:'记忆',exact:true}).click()
 if(await page.getByRole('button',{name:'开发版',exact:true}).isVisible())await page.getByRole('button',{name:'开发版',exact:true}).click()
 const root=page.locator('[data-native-workbench]');await root.waitFor();await root.getByRole('button',{name:'专注查看',exact:true}).click()
 await root.locator('[data-i5-nav=library]').click();await root.getByRole('button',{name:'追加笔记',exact:true}).click()
 const note=root.locator('.i5-note-page');await note.waitFor()
 await note.getByRole('textbox',{name:'追加项目笔记',exact:true}).fill('原生 UI 隔离验收草稿：保存前核对目标项目笔记。')
 check('note shows actual project destination',await note.locator('.i5-note-destination').innerText().then(t=>t.includes('项目笔记')&&t.includes('dsh-iter5-qa')))
 await capture('editor-note-1440',note)
 await page.setViewportSize({width:390,height:900});await capture('editor-note-390',note)
 await note.getByRole('button',{name:'取消',exact:true}).click();check('note cancel returns to library',await root.locator('.i5-file-list').count()===1)
 await page.setViewportSize({width:1440,height:1000});await root.locator('[data-i5-nav=calendar]').click();await root.getByRole('button',{name:/添加事项/}).click()
 const dlg=page.getByRole('dialog',{name:'添加日程',exact:true});await dlg.waitFor()
 check('calendar focuses title field',await dlg.getByRole('textbox',{name:'标题',exact:true}).evaluate(el=>el===document.activeElement))
 await dlg.getByRole('textbox',{name:'标题',exact:true}).fill('原生 UI 隔离验收 '+Date.now())
 event={title:await dlg.getByRole('textbox',{name:'标题',exact:true}).inputValue(),date:await dlg.locator('input[type=date]').inputValue(),time:await dlg.locator('input[type=time]').inputValue()}
 await capture('editor-calendar-1440',dlg);await page.setViewportSize({width:390,height:900});await capture('editor-calendar-390',dlg)
 await dlg.getByRole('button',{name:'添加日程',exact:true}).click();await dlg.waitFor({state:'detached'})
 await root.getByText(event.title,{exact:true}).waitFor();check('calendar saved item appears',await root.getByText(event.title,{exact:true}).count()===1)
 await root.getByRole('button',{name:'删除日程：'+event.title,exact:true}).click();await root.getByText(event.title,{exact:true}).waitFor({state:'detached'});checks.push('calendar actual save/delete roundtrip');event=null
 await page.setViewportSize({width:1440,height:1000});await root.locator('[data-i5-nav=storage]').click()
 const migration=root.locator('.i5-migration');await migration.waitFor()
 const out=path.join(process.env.TEMP,'dsh-iter5-qa-20260928','native-ui-export');fs.mkdirSync(out,{recursive:true})
 await migration.getByRole('textbox',{name:'输出目录',exact:true}).fill(out);await capture('migration-export',migration.locator('.i5-migration-export'))
 const exported=page.waitForResponse(r=>r.url().endsWith('/migrate-export')&&r.request().method()==='POST')
 await migration.locator('.i5-migration-export .i5-primary').click();const pack=await(await exported).json();check('real isolated export succeeds',pack.ok!==false&&!!pack.path)
 await migration.locator('.i5-migration-import input').first().fill(pack.path)
 await migration.locator('.i5-migration-import .i5-toolbar button').last().click();const preview=migration.locator('.i5-migration-preview');await preview.waitFor()
 check('preview renders actual conflict rows',await preview.locator('tbody tr').count()>0);await capture('migration-preview-1440',preview)
 await page.setViewportSize({width:390,height:900});await capture('migration-preview-390',preview)
 await preview.getByRole('button',{name:'取消预览',exact:true}).click();check('cancel preview performs no import',imported===0)
 await page.setViewportSize({width:1440,height:1000})
 const danger=root.locator('.i5-maintenance-danger');await danger.locator('select').selectOption({index:1});await danger.locator('input').fill('ui-review-cancel-only')
 await danger.getByRole('button',{name:'删除',exact:true}).click();const del=page.getByRole('dialog',{name:'确认删除记忆？',exact:true});await del.waitFor();await capture('delete-confirm',del)
 await del.getByRole('button',{name:'取消',exact:true}).click();check('cancel deletion sends no delete',deleted===0)
 await root.locator('[data-i5-nav=settings]').click();await root.getByRole('tab',{name:'外观与目录',exact:true}).click()
 await root.getByRole('button',{name:'选择模型 / 强度',exact:true}).click();const models=page.getByRole('dialog',{name:'子代理模型与思考强度',exact:true});await models.waitFor();await page.waitForTimeout(500)
 await capture('model-picker-1440',models);await page.setViewportSize({width:390,height:900});await capture('model-picker-390',models);await page.keyboard.press('Escape');check('model picker Escape closes',await models.count()===0)
 await page.setViewportSize({width:1440,height:1000})
 // Exercise the shipped remote/no-native-picker fallback; browse results remain live.
 await page.route('**/api/dsh-auto-memory/pick-dir',route=>route.fulfill({json:{native:false}}))
 await root.getByRole('button',{name:'浏览…',exact:true}).click()
 const folder=page.getByRole('dialog',{name:'选择记忆目录',exact:true});await folder.waitFor();await folder.locator('[data-native-path-browser] b').filter({hasText:'dsh-iter5-qa'}).waitFor()
 await capture('path-browser-fallback-1440',folder);await page.setViewportSize({width:390,height:900});await capture('path-browser-fallback-390',folder)
 await page.keyboard.press('Escape');await page.unroute('**/api/dsh-auto-memory/pick-dir');check('directory fallback cancel preserves config',await root.locator('[data-i5-dirty=true]').count()===0)
 await page.setViewportSize({width:1440,height:1000});await root.getByRole('tab',{name:'引擎',exact:true}).click()
 const guide=root.locator('[data-native-engine-guide=js]');await guide.waitFor();await capture('engine-install-ready',guide)
 engineChanged=true;await root.getByRole('radio',{name:/Python/}).click();await page.waitForFunction(()=>document.querySelector('[data-native-workbench] input[value=python]')?.checked)
 const python=root.locator('[data-native-python-wizard]');await python.waitFor();await python.locator('[data-native-python-step]').first().waitFor({timeout:60000})
 await capture('python-install-1440',python);await page.setViewportSize({width:390,height:900});await capture('python-install-390',python)
 check('no runtime errors',errors.length===0)
 fs.writeFileSync(path.join(__dirname,'editors-check.json'),JSON.stringify({checks,evidence,errors,limitations:['No import applied; preview and cancellation only.','Deletion canceled with an isolated nonexisting identifier.','Model list uses actual isolated host catalog; no model invocation.','Native directory picker unavailability injected; directory listing uses live host.','Python environment detection only; no dependency install or model download.']},null,2));console.log(JSON.stringify({passed:checks.length,errors}))
 }catch(e){console.log('Visible dialogs:',(await page.locator('[role=dialog]').allTextContents()).map(t=>t.slice(0,150)));throw e}finally{
 if(event)await page.evaluate(async event=>{await fetch('/api/dsh-auto-memory/calendar',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'remove',...event})})},event).catch(()=>{})
 if(engineChanged)await page.evaluate(async cfg=>{const r=await fetch('/api/dsh-auto-memory/config',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({semanticEngineMode:cfg.semanticEngineMode,activationSource:cfg.activationSource,contextSinkMode:cfg.contextSinkMode})});if(!r.ok)throw Error('Engine restoration failed')},config)
 await browser.close()
 }
})().catch(e=>{console.error(e.message);process.exitCode=1})
