const fs=require('node:fs'),path=require('node:path'),{createRequire}=require('node:module')
const {chromium}=createRequire('C:/Users/李云龙/dsh-auto-memory/docs/ui-redesign-2026-09-25/design-demos/package.json')('playwright')
;(async()=>{
 const browser=await chromium.launch({executablePath:path.join(process.env.LOCALAPPDATA,'ms-playwright/chromium_headless_shell-1228/chrome-headless-shell-win64/chrome-headless-shell.exe'),headless:true})
 const page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[]
 page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.dismiss())
 const url=fs.readFileSync(path.join(process.env.TEMP,'native-ui-host.log'),'utf8').match(/http:\/\/127\.0\.0\.1:19388\/\?token=\S+/)?.[0]
 await page.goto(url)
 if(await page.getByRole('button',{name:'继续',exact:true}).count())await page.getByRole('button',{name:'继续',exact:true}).click()
 await page.waitForTimeout(1800)
 if(await page.getByRole('button',{name:'稍后配置',exact:true}).count())await page.getByRole('button',{name:'稍后配置',exact:true}).click()
 if(await page.locator('[data-dam-tour]').count())await page.keyboard.press('Escape')
 await page.getByRole('treeitem',{name:'Iter5 隔离验收',exact:true}).click()
 await page.getByRole('treeitem',{name:/^UI 集成隔离验收/}).first().click()
 await page.getByRole('tab',{name:'记忆',exact:true}).click()
 if(await page.getByRole('button',{name:'开发版',exact:true}).isVisible())await page.getByRole('button',{name:'开发版',exact:true}).click()
 const root=page.locator('[data-native-workbench]');await root.waitFor();await page.waitForTimeout(900)
 await page.setViewportSize({width:390,height:900});await page.waitForTimeout(500)
 await page.screenshot({path:path.join(__dirname,'home-light-390.png')})
 await page.setViewportSize({width:1440,height:900})
 await page.locator('button[aria-label="设置"]').click();await page.getByRole('button',{name:'通用设置',exact:true}).click();await page.getByRole('button',{name:'深色',exact:true}).click();await page.getByRole('button',{name:'关闭',exact:true}).click()
 await page.waitForTimeout(600)
 await root.waitFor();await page.waitForTimeout(900)
 await page.screenshot({path:path.join(__dirname,'dark-home.png')})
 console.log(JSON.stringify({errors}))
 await browser.close()
})().catch(e=>{console.error(e.message);process.exitCode=1})
