const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{createRequire}=require('node:module')
const {chromium}=createRequire('C:/Users/李云龙/dsh-auto-memory/docs/ui-redesign-2026-09-25/design-demos/package.json')('playwright')
;(async()=>{
 const browser=await chromium.launch({executablePath:path.join(process.env.LOCALAPPDATA,'ms-playwright/chromium_headless_shell-1228/chrome-headless-shell-win64/chrome-headless-shell.exe'),headless:true})
 const page=await browser.newPage({viewport:{width:1440,height:900}}),checks=[],errors=[]
 page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.dismiss())
 const check=(name,ok)=>{assert(ok,name);checks.push(name)}
 try{
 const url=fs.readFileSync(path.join(process.env.TEMP,'native-ui-host.log'),'utf8').match(/http:\/\/127\.0\.0\.1:19388\/\?token=\S+/)?.[0];assert(url)
 await page.goto(url)
 if(await page.getByRole('button',{name:'继续',exact:true}).count())await page.getByRole('button',{name:'继续',exact:true}).click()
 await page.waitForTimeout(1200)
 if(await page.getByRole('button',{name:'稍后配置',exact:true}).count())await page.getByRole('button',{name:'稍后配置',exact:true}).click()
 if(await page.locator('[data-dam-tour]').count())await page.keyboard.press('Escape')
 const config=await page.evaluate(async()=> (await(await fetch('/api/dsh-auto-memory/config')).json()).config)
 check('isolated roots',config.memoryRoot.includes('dsh-iter5-qa-20260928')&&config.userMemoryDir.includes('dsh-iter5-qa-20260928'))
 await page.getByRole('treeitem',{name:'Iter5 隔离验收',exact:true}).click()
 await page.getByRole('treeitem',{name:/^UI 集成隔离验收/}).first().click()
 await page.getByRole('tab',{name:'记忆',exact:true}).click()
 if(await page.getByRole('button',{name:'开发版',exact:true}).isVisible())await page.getByRole('button',{name:'开发版',exact:true}).click()
 const root=page.locator('[data-native-workbench]');await root.waitFor()
 await root.getByRole('button',{name:'专注查看',exact:true}).click()
 check('native workbench mounts',await root.locator('.i5-window-bar').count()===1)
 await root.locator('[data-i5-nav=mindmap]').click();await root.locator('.i5-native-map svg').waitFor()
 for(const width of [1440,390]){
 await page.setViewportSize({width,height:900});await page.waitForTimeout(300)
 await root.getByRole('button',{name:'适应',exact:true}).click()
 const map=root.locator('.i5-native-map')
 check(width+' fit contains graph width',await map.evaluate(el=>el.scrollWidth<=el.clientWidth+1))
 check(width+' fit contains graph height',await map.evaluate(el=>el.scrollHeight<=el.clientHeight+1))
 check(width+' all nodes have keyboard affordances',await map.locator('[data-native-map-node][tabindex="0"]').count()===await map.locator('[data-native-map-node]').count())
 if(process.env.NATIVE_CAPTURE==='1')await page.screenshot({path:path.join(__dirname,'map-'+width+'.png')})
 }
 await page.setViewportSize({width:1440,height:900});await page.waitForTimeout(200)
 const map=root.locator('.i5-native-map'),before=await map.locator('svg').getAttribute('width')
 await root.getByRole('button',{name:'放大关系图',exact:true}).click()
 check('zoom increases actual svg dimensions',Number(await map.locator('svg').getAttribute('width'))>Number(before))
 await map.evaluate(el=>{el.scrollLeft=30;el.scrollTop=20})
 await root.getByRole('button',{name:'适应',exact:true}).click()
 check('Fit resets pan',await map.evaluate(el=>el.scrollLeft===0&&el.scrollTop===0))
 await root.getByRole('combobox',{name:'关系图范围',exact:true}).selectOption('__all')
 await page.waitForTimeout(100)
 check('all workspace overview remains available',await map.locator('[data-native-map-node=workspace]').count()>1)
 const nodes=map.locator('[data-native-map-node=workspace]')
 if(await nodes.count()>1){const label=await nodes.nth(1).getAttribute('aria-label');await nodes.nth(1).focus();await page.keyboard.press('Enter');check('keyboard selection changes detail',await root.locator('.i5-map-detail h2').innerText()===label)}
 check('no runtime errors',errors.length===0)
 fs.writeFileSync(path.join(__dirname,'map-check.json'),JSON.stringify({checks,errors},null,2));console.log(JSON.stringify({passed:checks.length,errors}))
 }catch(e){console.log('Visible dialogs:',(await page.locator('[role=dialog]').allTextContents()).map(t=>t.slice(0,200)));throw e}finally{await browser.close()}
})().catch(e=>{console.error(e.message);process.exitCode=1})
